# This is a basic workflow to help you get started with Actions

name: Dynamic Profile

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run dynamic-profile
        run: npx github:matthewtole/dynamic-profile

      - name: Simple commit
        uses: zwaldowski/git-commit-action@v1
